#!/usr/bin/env python3
"""
Standalone script to cleanup test data generated by generate_test_data.py

This script deletes the "Direction Générale" organization unit, which will
cascade delete all children (organization units and positions).

Usage:
    python cleanup_test_data.py
    
Or with custom Python environment:
    /path/to/venv/bin/python cleanup_test_data.py
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

from conftest import get_service_logger
import requests

logger = get_service_logger('cleanup_data')

# Load environment variables
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '.env.test'))


def main():
    """Cleanup test data by deleting Direction Générale (cascade delete)."""
    
    # Configuration from .env.test
    base_url = os.getenv('WEB_URL')
    login = os.getenv('LOGIN')
    password = os.getenv('PASSWORD')
    
    logger.info("=" * 80)
    logger.info("🧹 Cleanup Test Data - Delete Direction Générale")
    logger.info("=" * 80)
    logger.info(f"Base URL: {base_url}")
    logger.info(f"Login: {login}")
    
    # Step 1: Authenticate
    logger.info("\n🔐 Step 1: Authenticating...")
    session = requests.Session()
    session.verify = False  # Disable SSL verification for local testing
    
    login_response = session.post(
        f"{base_url}/api/auth/login",
        json={"email": login, "password": password}
    )
    
    if login_response.status_code != 200:
        logger.error(f"❌ Login failed: {login_response.status_code} - {login_response.text}")
        return 1
    
    cookies = {
        'access_token': login_response.cookies.get('access_token'),
        'refresh_token': login_response.cookies.get('refresh_token')
    }
    
    # Get company_id
    verify_response = session.get(
        f"{base_url}/api/auth/verify",
        cookies=cookies
    )
    
    if verify_response.status_code != 200:
        logger.error(f"❌ Verify failed: {verify_response.status_code}")
        return 1
    
    company_id = verify_response.json()['company_id']
    logger.info(f"✅ Authenticated - Company ID: {company_id}")
    
    # Step 2: Find Direction Générale
    logger.info("\n🔍 Step 2: Finding 'Direction Générale'...")
    
    list_response = session.get(
        f"{base_url}/api/identity/organization_units",
        cookies=cookies
    )
    
    if list_response.status_code != 200:
        logger.error(f"❌ Failed to list organization units: {list_response.status_code}")
        return 1
    
    org_units = list_response.json()
    direction_generale = None
    
    for unit in org_units:
        if unit.get('name') == 'Direction Générale':
            direction_generale = unit
            break
    
    if not direction_generale:
        logger.warning("⚠️ 'Direction Générale' not found - nothing to clean up")
        logger.info("💡 Maybe it was already deleted, or data was never generated?")
        return 0
    
    logger.info(f"✅ Found 'Direction Générale': {direction_generale['id']}")
    
    # Step 3: Count children before deletion
    logger.info("\n📊 Step 3: Counting data to delete...")
    
    # Count direct children
    children = [u for u in org_units if u.get('parent_id') == direction_generale['id']]
    logger.info(f"  • Direct children: {len(children)}")
    logger.info(f"  • Total organization units: {len(org_units)}")
    
    # Count positions
    positions_response = session.get(
        f"{base_url}/api/identity/positions",
        cookies=cookies
    )
    
    if positions_response.status_code == 200:
        positions = positions_response.json()
        logger.info(f"  • Total positions: {len(positions)}")
    
    # Step 4: Delete Direction Générale (cascade)
    logger.info("\n🗑️ Step 4: Deleting 'Direction Générale' (cascade delete)...")
    
    confirm = input("\n⚠️  This will delete ALL organization units and positions. Continue? [y/N]: ")
    
    if confirm.lower() != 'y':
        logger.info("❌ Cleanup cancelled by user")
        return 0
    
    delete_response = session.delete(
        f"{base_url}/api/identity/organization_units/{direction_generale['id']}",
        cookies=cookies
    )
    
    if delete_response.status_code == 204:
        logger.info("\n" + "=" * 80)
        logger.info("✅ SUCCESS - All test data deleted!")
        logger.info("=" * 80)
        logger.info("📝 Deleted:")
        logger.info("  • Direction Générale (root)")
        logger.info(f"  • All {len(org_units) - 1} child organization units (cascade)")
        logger.info("  • All positions (cascade)")
        return 0
    else:
        logger.error(f"\n❌ Delete failed: {delete_response.status_code} - {delete_response.text}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
